language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
matrix:
  allow_failures:
    - python: "pypy"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install coveralls
# command to run tests
script: py.test coursera/test -v --cov coursera --cov-report html

after_success:
  coveralls
